name: UzPolis Frontend CI/CD Pipeline

on:
  push:
    branches:
      - prod # Frontendchilar kodi qaysi branchga push qilinishini tekshiring

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # Imaj nomi: j-onfroy/uzpolis-web bo'ladi
  IMAGE_NAME: ${{ github.repository_owner }}/uzpolis-web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. GitHub'dan kodni o'qib olish
        uses: actions/checkout@v3

      - name: 2. GitHub Container Registry (GHCR) ga ulanish
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3. Docker imaj yaratish va GHCR ga yuklash
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: 4. Serverda Docker konteynerini yangilash
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/ubuntu/uzpolis 
            
            # Serverni GitHub Registry'ga login qilish (Private imaj uchun)
            sudo docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GH_PAT }}
            
            # Yangi frontend imajini tortib olish
            sudo docker-compose pull uzpolis-web
            
            # Faqat frontendni (uzpolis-web) qayta ishga tushirish
            sudo docker-compose up -d uzpolis-web
          
            sudo docker image prune -a -f