name: Auto Build and Deploy

on:
  push:
    branches:
      - main  # Prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Har doim 'latest' tagi bilan build qiladi
          tags: ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # Build tugamaguncha serverga tegmaydi

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # GHCR-dan yangi imagni tortish
            echo ${{ secrets.GITHUB_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            sudo docker pull ghcr.io/${{ github.repository }}:latest
            
            # Konteynerni yangilash
            sudo docker stop front-container || true
            sudo docker rm front-container || true
            
            # Konteynerni ishga tushirish (8080:80 qismini Nginx-ga qarab to'g'irlab oling)
            sudo docker run -d \
              --name front-container \
              --restart always \
              -p 8080:80 \
              ghcr.io/${{ github.repository }}:latest
            
            # Tozalash
            sudo docker image prune -f